version: '3'

services:
  mongo:
    container_name: mongodb
    restart: always
    image: mongo
    environment:
      MONGO_INITIOS_ROOT_USERNAME: 'devbills'
      MONDO_INITIOS_ROOT_PASSWORD: 'pass123'
    ports:
      - "27017:27017"

  app:
    depends_on:
      - mongo
    container_name: devbills-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'